### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined when using options

### ISSUE THREAD

**Issue by MarioGiancini** [retextjs/retext-keywords#18]
### Subject of the issue

When using the default example given in the readme, adding an `options` object with `maximum` value causes an error.

### Environment

-   **OS**: `OSX Mojave 10.14.4 `
-   **Packages**:

| Package        | Version      |
| ------------- | ---------- | 
| `retext`   | ^7.0.1 | 
| `retext-keywords` | ^5.0.0      |  
|`nlcst-to-string` | latest   |
|`retext-pos` | ^2.0.2  |
|`to-vfile` | ^6.0.0  |

-   **Env**: 

| Package        | Version      |
| ------------- | ---------- | 
| `node`   | 8.7.0 |
| 'npm'  | 6.13.1 |

### Steps to reproduce

1. Start a new project in a clean directory
2. `npm instal retext`
3. `npm install retext-keywords`
4. `npm install nlcst-to-string`
5. `npm install retext-pos`
6. `npm install to-vfile`
7. create a file called `index.js`
8. copy the contents of the example given in the readme
9. create the `example.txt` file in the same directory
9. add an `options` object to the `keywords` with a `maximum: 8`
10. run `node index`

### Expected behaviour

We should see a similar console log but with around 8 keywords and phrase

### Actual behaviour

This error is throw:

```
/Users/Mario/Sites/retext-test/node_modules/unist-util-visit-parents/index.js:41
    if (node.children && result[0] !== SKIP) {
             ^

TypeError: Cannot read property 'children' of undefined
    at one (/Users/Mario/Sites/retext-test/node_modules/unist-util-visit-parents/index.js:41:14)
    at visitParents (/Users/Mario/Sites/retext-test/node_modules/unist-util-visit-parents/index.js:26:3)
    at visit (/Users/Mario/Sites/retext-test/node_modules/unist-util-visit/index.js:22:3)
    at getImportantWords (/Users/Mario/Sites/retext-test/node_modules/retext-keywords/index.js:214:3)
    at Function.transformer (/Users/Mario/Sites/retext-test/node_modules/retext-keywords/index.js:17:21)
    at freeze (/Users/Mario/Sites/retext-test/node_modules/unified/index.js:118:28)
    at Function.process (/Users/Mario/Sites/retext-test/node_modules/unified/index.js:352:5)
    at Object.<anonymous> (/Users/Mario/Sites/retext-test/index.js:14:6)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

Please see attached example project.
[retext-test.zip](https://github.com/retextjs/retext-keywords/files/3924390/retext-test.zip)

**Comment by wooorm** [comment]
Sorry for letting this set so long, and thanks for the example code! In [unified](https://unifiedjs.com), options are passed like this:

```js
  // ...
  .use(keywords, options)
  // ...
```

That should solve it!
